version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GRAPHQL_URI=http://localhost:4000/graphql
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped
