services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 3000:3000
    depends_on:
      - backend
