version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_GRAPHQL_URI=http://back:4000/graphql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
